export const parts = [
  { id: 1, label: 'Part I：瀏覽器底層運作' },
  { id: 2, label: 'Part II：HTML 語意與架構' },
  { id: 3, label: 'Part III：CSS 全面掌握' },
  { id: 4, label: 'Part IV：資源載入策略與 Performance' },
  { id: 5, label: 'Part V：WebAssembly 全景' },
  { id: 6, label: 'Part VI：Canvas 與 WebGL' },
  { id: 7, label: 'Part VII：效能優化全景' },
  { id: 8, label: 'Part VIII：GenAI 整合模式' },
  { id: 9, label: 'Appendices：面試速查與決策樹' },
]

export const chapters = [
  chapter(1, 1, 'url-to-pixels', '從 URL 到像素的完整旅程', ['browser', 'network'], [
    ['overview', '高層次全景'],
    ['url-parsing', 'URL Parsing 與 Scheme 處理'],
    ['dns-connection', 'DNS Resolution 與 Connection Pooling'],
    ['tls-handshake', 'TLS Handshake 與 0-RTT'],
    ['http-lifecycle', 'HTTP Request 與 Response Lifecycle'],
  ], 'URL 到畫面的路徑不是單一流程，而是網路、快取、安全、解析與渲染互相交錯的 pipeline。'),
  chapter(2, 1, 'parsing-rendering-pipeline', 'Parsing 與 Rendering Pipeline', ['browser', 'rendering'], [
    ['html-parser', 'HTML Parser 與 Tokenization'],
    ['dom-construction', 'DOM 建構'],
    ['cssom', 'CSSOM 建構與 render-blocking'],
    ['render-layout-paint-composite', 'Render Tree、Layout、Paint、Composite'],
    ['threads', '主執行緒、Compositor Thread、Raster Thread'],
    ['browser-process', 'Browser Process 架構'],
  ], 'Senior 前端要能把 DevTools Performance 的事件對回瀏覽器內部工作，而不是只說「瀏覽器會 render」。'),
  chapter(3, 2, 'semantic-html-structure', '語意化 HTML 與文件結構', ['html', 'a11y'], [
    ['outline-heading', 'Document Outline 與 Heading Hierarchy'],
    ['inline-block-replaced', 'Inline vs Block vs Replaced Elements'],
    ['meta-tags', 'meta Tags 與文件元資訊'],
    ['structured-data', 'Microdata、JSON-LD 與 Structured Data'],
  ], '語意化 HTML 的價值在於讓瀏覽器、搜尋引擎、輔助科技與維護者都讀得懂同一份文件。'),
  chapter(4, 2, 'forms-interactive-elements', '表單與互動元素', ['html', 'forms'], [
    ['form-overview', 'Form Element 全景'],
    ['native-validation', '原生 Form Validation'],
    ['formdata', 'Form Submission 與 FormData'],
    ['contenteditable', 'ContentEditable 與 Rich Text Editing'],
  ], '表單是 Web 平台最成熟的互動模型，Senior 工程師要知道何時用 native behavior，而不是全部重寫。', 'form'),
  chapter(5, 2, 'html5-api-metadata', 'HTML5 API 與 Metadata', ['html', 'platform'], [
    ['dialog-popover', 'dialog 與 Popover API'],
    ['details-summary', 'details / summary 與 Disclosure Widget'],
    ['media-elements', 'Media Elements'],
    ['canvas-svg-webgl-webgpu', 'Canvas、SVG、WebGL、WebGPU'],
  ], '新的平台 API 正在把許多過去靠 portal、positioning library 或自製 widget 的功能收回瀏覽器原生層。'),
  chapter(6, 3, 'css-cascade-basics', 'CSS 基礎與級聯機制', ['css'], [
    ['box-model', 'Box Model 與 box-sizing'],
    ['specificity', 'Selectors 與 Specificity 計算'],
    ['cascade', 'Cascade、Inheritance、Importance'],
    ['custom-properties', 'CSS Custom Properties'],
    ['values-units-functions', 'Values、Units、Functions'],
  ], 'CSS 的困難不在語法，而在 cascade、layout algorithm 與元件邊界之間的互動。', 'specificity'),
  chapter(7, 3, 'layout-systems', 'Layout 系統', ['css', 'layout'], [
    ['normal-flow-positioning', 'Normal Flow 與 Positioning'],
    ['flexbox', 'Flexbox 深度解析'],
    ['grid', 'Grid 深度解析'],
    ['container-queries', 'Container Queries 與 Intrinsic Layout'],
    ['logical-properties', 'Logical Properties 與 i18n'],
  ], '現代 layout 不該只靠 viewport media query；好的元件會回應自己的容器、內容與書寫方向。', 'box'),
  chapter(8, 3, 'responsive-modern-css', '響應式設計與現代 CSS', ['css', 'rwd'], [
    ['media-queries', 'Media Queries 演進'],
    ['dark-mode', 'Dark Mode 與 Theming'],
    ['animations', 'Animations 與 Transitions'],
    ['modern-css', '現代 CSS 新特性總覽'],
  ], 'RWD 已從斷點設計演進到能力查詢、偏好查詢、容器查詢與使用者設定的整合。'),
  chapter(9, 3, 'css-architecture', 'CSS 架構與可維護性', ['css', 'architecture'], [
    ['naming', '命名方法論：BEM、SMACSS、OOCSS'],
    ['css-in-js-modules-utility', 'CSS-in-JS vs CSS Modules vs Utility-first'],
    ['constructable-stylesheets', 'Constructable Stylesheets 與 Shadow DOM 整合'],
  ], 'CSS 架構的核心是控制作用域、依賴順序與設計 token，而不是追求某個命名流派的純度。'),
  chapter(10, 4, 'javascript-loading', 'JavaScript 載入策略', ['performance', 'javascript'], [
    ['script-model', 'script 標籤的執行模型'],
    ['esm-import-maps', 'ES Modules 與 Import Maps'],
    ['bundler-code-splitting', 'Bundler 與 Code Splitting'],
    ['lazy-loading', 'Lazy Loading 與 On-demand Loading'],
    ['workers', 'Worker 模型'],
  ], 'JS 載入策略直接決定 parser blocking、主執行緒壓力與首次互動能力。'),
  chapter(11, 4, 'font-loading', 'Font 載入與字型優化', ['performance', 'font'], [
    ['font-loading', 'Font Loading 全景'],
    ['formats-subsetting', 'Font Format 與 Subsetting'],
    ['optional-cls', 'font-display optional 與 CLS 防範'],
    ['preload-font', 'Preload 字型的最佳實踐'],
  ], '字型優化不只是壓檔案，而是平衡品牌一致性、可讀性、FOIT/FOUT 與 layout shift。'),
  chapter(12, 4, 'image-media-optimization', 'Image 與媒體資源優化', ['performance', 'media'], [
    ['formats', '圖片格式選擇'],
    ['responsive-images', 'Responsive Images'],
    ['lazy-loading', 'Lazy Loading 與 loading=lazy'],
    ['aspect-ratio-cls', 'Aspect Ratio 與 CLS 防範'],
  ], '圖片通常是 LCP 最大來源；選格式、尺寸、優先級與保留空間比單純壓縮更重要。'),
  chapter(13, 4, 'resource-hints-network', 'Resource Hints 與網路層優化', ['performance', 'network'], [
    ['resource-hints', 'Resource Hints 完整對照'],
    ['http2-http3', 'HTTP/2、HTTP/3 與 Multiplexing'],
    ['compression', 'Compression：gzip、Brotli、Zstandard'],
    ['speculation-rules', 'Speculation Rules API'],
  ], 'Resource hint 是對瀏覽器排程器下提示，不是越多越好；錯誤 preload 會搶走真正 critical resource。', 'resources'),
  chapter(14, 4, 'caching-strategies', 'Caching 策略', ['performance', 'cache'], [
    ['http-cache', 'HTTP Cache'],
    ['cache-hierarchy', 'Cache Hierarchy'],
    ['service-worker-cache', 'Service Worker 快取策略'],
    ['application-cache', 'Application-Level Caching'],
  ], '快取設計的重點是 freshness、invalidation 與 fallback，不只是把東西存起來。'),
  chapter(15, 4, 'core-web-vitals-rum', 'Core Web Vitals 與 RUM', ['performance', 'metrics'], [
    ['lcp', 'LCP'],
    ['inp', 'INP'],
    ['cls', 'CLS'],
    ['other-metrics', 'TTFB、FCP、TTI 與其他輔助指標'],
    ['rum-synthetic', 'RUM vs Synthetic Monitoring'],
  ], 'Core Web Vitals 是使用者體感的 proxy；Senior 要能從指標回推可執行的修復策略。'),
  chapter(16, 5, 'wasm-origin-model', 'WebAssembly 起源與設計哲學', ['wasm'], [
    ['asmjs-to-wasm', '從 asm.js 到 Wasm 的演進'],
    ['execution-model', 'Module、Instance、Memory、Table 的執行模型'],
    ['sandbox-security', 'Sandbox Security Model'],
    ['promise-limitations', 'Wasm 的核心承諾與限制'],
    ['blazor', 'Blazor WebAssembly 與 Microsoft 生態'],
  ], 'Wasm 是低階可攜式執行格式，不是取代 JavaScript 的 UI 語言。'),
  chapter(17, 5, 'wasm-toolchain', 'Wasm Toolchain 與語言生態', ['wasm', 'tooling'], [
    ['toolchain-map', '主流編譯路徑全景'],
    ['emscripten', 'Emscripten 深度解析'],
    ['rust-wasm-bindgen', 'Rust + wasm-bindgen'],
    ['assemblyscript', 'AssemblyScript'],
    ['dotnet-csharp', '.NET / C# 到 Wasm 的特殊性'],
  ], '選 toolchain 要看既有 codebase、runtime 成本、bundle 大小與團隊維護能力。'),
  chapter(18, 5, 'wasm-js-interop', 'Wasm 與 JavaScript 的互通機制', ['wasm', 'javascript'], [
    ['instantiate', '載入與實例化的最佳實踐'],
    ['linear-memory', 'Linear Memory 與零拷貝模式'],
    ['boundary-cost', '函式呼叫的 Boundary Cost'],
    ['wasm-gc', 'Wasm GC 與 Reference Types'],
  ], 'Wasm 效能常輸在 JS/Wasm boundary；能否批次傳資料比單次函式速度更關鍵。'),
  chapter(19, 5, 'wasm-real-world', 'Wasm 在前端的實戰場景', ['wasm', 'case-study'], [
    ['media-processing', '影像與媒體處理'],
    ['crypto-compression', '加密、壓縮與資料處理'],
    ['case-studies', '大型應用案例研究'],
    ['edge-ml', '端側 ML 推論'],
    ['when-not', '何時不該用 Wasm'],
  ], 'Wasm 最適合計算密集、既有 native codebase 或需要可預測效能的模組。'),
  chapter(20, 5, 'wasm-advanced-future', 'Wasm 進階主題與未來', ['wasm', 'future'], [
    ['wasi', 'WASI 與瀏覽器外的 Wasm'],
    ['component-model', 'Component Model 與 WIT'],
    ['threads-sab', 'Wasm + Web Worker + SharedArrayBuffer'],
    ['debug-profiling', 'Wasm Debugging 與 Profiling'],
  ], 'Wasm 正從瀏覽器外掛能力，演進成 edge runtime、component model 與多語言模組邊界。'),
  chapter(21, 6, 'canvas-2d', 'Canvas 2D 深入解析', ['canvas'], [
    ['canvas-svg-dom', 'Canvas vs SVG vs DOM 的根本差異'],
    ['context-api', 'Canvas 2D Context API 全景'],
    ['pixels-filter', '像素級操作與 Filter'],
    ['text-rendering', '文字渲染的隱藏複雜度'],
    ['hidpi', 'HiDPI 與 Device Pixel Ratio'],
    ['hit-testing-a11y', 'Hit Testing 與 Accessibility'],
  ], 'Canvas 是 immediate mode；效能與彈性換來的是自行管理場景、命中測試與可訪問性。', 'canvas'),
  chapter(22, 6, 'offscreen-canvas-worker', 'OffscreenCanvas 與 Worker 渲染', ['canvas', 'worker'], [
    ['why-worker', '為什麼要把渲染搬離主執行緒'],
    ['offscreen-api', 'OffscreenCanvas API 與資源轉移'],
    ['imagebitmap', 'ImageBitmap 與零拷貝資料傳遞'],
  ], 'OffscreenCanvas 的價值是讓重繪與主執行緒互動分離，避免輸入延遲被繪圖拖累。'),
  chapter(23, 6, 'webgl-basics', 'WebGL 基礎', ['webgl'], [
    ['what-is-webgl', 'WebGL 是什麼，又不是什麼'],
    ['gpu-pipeline', 'GPU Rendering Pipeline'],
    ['glsl', 'GLSL Shader 程式設計'],
    ['buffers-textures-framebuffers', 'Buffer、Texture、Framebuffer'],
    ['draw-call-cost', 'Draw Call 與 State Change 成本'],
  ], 'WebGL 是畫三角形的低階 API；Three.js 等引擎只是把常見圖學抽象包起來。', 'gpu'),
  chapter(24, 6, 'webgl-advanced-performance', 'WebGL 進階與效能優化', ['webgl', 'performance'], [
    ['instancing-batching', 'Instancing 與 Batching'],
    ['framebuffer-post', 'Framebuffer Object 與後處理'],
    ['context-loss', 'Context Loss 與 Recovery'],
    ['avoid-raw-webgl', '何時不要直接寫 WebGL'],
  ], 'WebGL 效能往往卡在 CPU-side draw call 與 state change，而不是 GPU 算不動。'),
  chapter(25, 6, 'webgpu', 'WebGPU——下一代 GPU API', ['webgpu'], [
    ['why-webgpu', '為什麼 WebGL 不夠用'],
    ['compute-shader', 'Compute Shader 與 GPGPU'],
    ['wgsl', 'WGSL 著色語言'],
    ['browser-support', 'WebGPU 的瀏覽器支援現況'],
    ['genai-inference', 'WebGPU 加速 GenAI 推論'],
  ], 'WebGPU 把現代 GPU API 帶到瀏覽器，尤其讓 compute shader 成為前端可用能力。', 'gpu'),
  chapter(26, 6, 'canvas-webgl-genai', 'Canvas 與 WebGL 在 GenAI 場景的應用', ['genai', 'canvas'], [
    ['progress-visualization', 'AI 圖像生成的進度視覺化'],
    ['controlnet-input', 'ControlNet 與互動式繪圖輸入'],
    ['image-editor-ui', 'AI 影像編輯工具 UI 設計'],
    ['large-data-viz', '大規模資料視覺化與 GenAI 整合'],
    ['multimodal-future', '多模態 GenAI 介面的未來'],
  ], 'GenAI UI 不會停在文字輸入框；Canvas/WebGL 是多模態互動的操作層。'),
  chapter(27, 7, 'rendering-performance', 'Rendering Performance', ['performance', 'rendering'], [
    ['frame-budget', '60fps 與 Frame Budget'],
    ['layout-thrashing', 'Layout Thrashing 與 Forced Synchronous Layout'],
    ['containment', 'will-change、contain、content-visibility'],
    ['virtualization', 'Virtualization 深入'],
    ['gpu-compositing', 'GPU Compositing 與圖層管理'],
  ], 'Rendering performance 的關鍵是把 style/layout/paint/composite 拆開診斷，不要只看 FPS。'),
  chapter(28, 7, 'javascript-execution-performance', 'JavaScript 執行效能', ['performance', 'javascript'], [
    ['v8-optimization', 'V8 內部優化機制'],
    ['micro-optimization', 'Loop、Object Creation、Allocation'],
    ['scheduling', 'Scheduling APIs'],
    ['concurrent-rendering', 'Concurrent Rendering 與 Transitions'],
  ], 'JS 效能優化要先找熱路徑與互動延遲，再決定要拆 task、減 allocation 或調整 framework scheduling。'),
  chapter(29, 7, 'memory-management', 'Memory 管理與洩漏防範', ['performance', 'memory'], [
    ['memory-model', 'JavaScript Memory Model'],
    ['leak-patterns', '常見記憶體洩漏模式'],
    ['devtools-memory', 'DevTools Memory 工具'],
    ['web-components-memory', 'Web Components 與記憶體'],
  ], '記憶體問題常表現為越用越慢；Senior 要能用 snapshot 找 retained path，而不是只重整頁面。'),
  chapter(30, 8, 'streaming-ui-patterns', 'Streaming UI 模式', ['genai', 'streaming'], [
    ['sse-websocket-fetch', 'SSE vs WebSocket vs Streaming Fetch'],
    ['token-rendering', 'Streaming Token Rendering'],
    ['markdown-streaming', 'Markdown Streaming Parsing'],
    ['citation', 'Citation 與 Source Reference'],
    ['scroll-lock', 'Scroll Lock 與 Auto-scroll'],
  ], 'LLM streaming 是資料流、排版、滾動、可訪問性與取消狀態一起設計的 UI 問題。', 'streaming'),
  chapter(31, 8, 'intelligent-interaction-components', '智慧型互動元件', ['genai', 'ui'], [
    ['autocomplete', 'LLM-Powered Autocomplete'],
    ['chat-composer', 'GenAI Chat Input Composer'],
    ['conversation-tree', 'Multi-turn Branching 與 Conversation Tree'],
    ['optimistic-cancel', 'Optimistic Updates 與 Cancel 模式'],
    ['genai-a11y', 'Accessibility 在 GenAI UI 的挑戰'],
  ], 'GenAI 元件需要處理 abort、partial state、IME、附件、分支、引用與 screen reader 節流。', 'composer'),
  chapter(32, 9, 'appendix-http-status', 'Appendix A：HTTP Status Code 完整對照表', ['appendix', 'http'], [
    ['status-table', 'Status Code 對照表'],
    ['redirects', 'Redirect 語意'],
    ['auth-errors', '401 vs 403'],
  ], 'HTTP status code 是前後端 contract，不只是 debug 時看 network tab 的數字。'),
  chapter(33, 9, 'appendix-css-specificity', 'Appendix B：CSS Specificity 計算器與範例', ['appendix', 'css'], [
    ['calculator', 'Specificity 計算器'],
    ['where-is-has', ':where、:is、:has'],
    ['debugging', 'Debugging 流程'],
  ], 'Specificity 問題要用 cascade 層級和作用域治理，不是一直加 !important。', 'specificity'),
  chapter(34, 9, 'appendix-resource-hints', 'Appendix C：Resource Hints 決策樹', ['appendix', 'performance'], [
    ['decision-tree', '決策樹'],
    ['cross-origin', '跨域注意事項'],
    ['anti-patterns', '常見反模式'],
  ], 'Resource hints 的問題永遠是：你要提前做哪一件昂貴工作，以及它是否真的會被使用。', 'resources'),
  chapter(35, 9, 'appendix-wasm-toolchain', 'Appendix D：Wasm 工具鏈速查表', ['appendix', 'wasm'], [
    ['language-map', '來源語言對照'],
    ['bundle-cost', '產物大小與 runtime 成本'],
    ['selection', '選型建議'],
  ], 'Wasm toolchain 選型是產品限制、團隊能力與既有資產的交集。'),
  chapter(36, 9, 'appendix-graphics-decision', 'Appendix E：Canvas / WebGL / WebGPU 選擇決策樹', ['appendix', 'graphics'], [
    ['decision-tree', '技術選型決策樹'],
    ['fallbacks', 'Fallback 策略'],
    ['a11y', '可訪問性補償'],
  ], '繪圖技術選型要同時看節點數、互動頻率、可訪問性、GPU 需求與團隊熟悉度。', 'gpu'),
  chapter(37, 9, 'appendix-web-vitals-checklist', 'Appendix F：Core Web Vitals 優化 Checklist', ['appendix', 'performance'], [
    ['lcp-checklist', 'LCP Checklist'],
    ['inp-checklist', 'INP Checklist'],
    ['cls-checklist', 'CLS Checklist'],
  ], 'Checklist 的價值不是照單全收，而是幫你在診斷後快速找到最可能的修復槓桿。'),
  chapter(38, 9, 'appendix-senior-signal', 'Appendix G：Senior Front-End Interview Signal Checklist', ['appendix', 'interview'], [
    ['tradeoff', '能說 trade-off'],
    ['not-use', '能說何時不該用'],
    ['spec-level', '能說 spec-level 細節'],
    ['browser-link', '能連到底層瀏覽器行為'],
  ], 'Senior signal 不是背更多 API，而是能把產品需求、平台限制、效能與可維護性連成一條可辯護的決策鏈。'),
]

function chapter(id, part, slug, title, tags, sections, thesis, demo = null) {
  return {
    id,
    part,
    slug,
    title,
    tags,
    thesis,
    demo,
    sections: sections.map(([sectionSlug, sectionTitle]) => ({ slug: sectionSlug, title: sectionTitle })),
  }
}

export const chapterMap = Object.fromEntries(chapters.map(chapter => [chapter.id, chapter]))
